exclude = ["alembic"]

[lint]
# ignore equality comparisons to `True` and `None`
# ignore return type annotations
ignore = ["E711", "E712", "ANN201", "ANN204"]
# sort imports
# enforce type annotations
# enforce non-blocking calls in async functions
extend-select = ["I", "ANN", "ASYNC"]
