"""add trigger response type

Revision ID: 01620645b7bd
Revises: 09214f192b54
Create Date: 2025-07-22 12:17:20.186423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01620645b7bd'
down_revision: Union[str, None] = '09214f192b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

response_type_enum = sa.Enum('standard', 'reply', 'reaction', name='triggerresponsetype')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    response_type_enum.create(op.get_bind())
    op.add_column('trigger_group', sa.Column('response_type', sa.Enum('standard', 'reply', 'reaction', name='triggerresponsetype'), server_default='standard', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trigger_group', 'response_type')
    response_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
