"""add timezone to user table

Revision ID: 09214f192b54
Revises: bec671a2dd49
Create Date: 2025-03-11 03:42:52.229709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09214f192b54'
down_revision: Union[str, None] = 'bec671a2dd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pzsd_user', sa.Column('timezone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pzsd_user', 'timezone')
    # ### end Alembic commands ###
