"""Add point_giver column to user table

Revision ID: 14f002fc4966
Revises: c04346189431
Create Date: 2024-09-17 12:56:41.005115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f002fc4966'
down_revision: Union[str, None] = 'c04346189431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pzsd_user', sa.Column('point_giver', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pzsd_user', 'point_giver')
    # ### end Alembic commands ###
