"""Make discord snowflake optional for users

Revision ID: 8905ff0b3cc2
Revises: ada18e8c9983
Create Date: 2024-04-04 01:40:20.690883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8905ff0b3cc2'
down_revision: Union[str, None] = 'ada18e8c9983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pzsd_user', 'discord_snowflake',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pzsd_user', 'discord_snowflake',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
