"""Enforce unique user name and snowflake

Revision ID: ada18e8c9983
Revises: e0d89d644b1b
Create Date: 2024-03-30 00:45:39.784302

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ada18e8c9983"
down_revision: Union[str, None] = "e0d89d644b1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "pzsd_user", ["discord_snowflake"])
    op.create_unique_constraint(None, "pzsd_user", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pzsd_user", type_="unique")
    op.drop_constraint(None, "pzsd_user", type_="unique")
    # ### end Alembic commands ###
