"""add trigger tables

Revision ID: bf4945378c82
Revises: 14f002fc4966
Create Date: 2025-02-19 02:09:40.032044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4945378c82'
down_revision: Union[str, None] = '14f002fc4966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trigger_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('owner', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_pattern',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['trigger_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['trigger_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trigger_response')
    op.drop_table('trigger_pattern')
    op.drop_table('trigger_group')
    # ### end Alembic commands ###
