"""Add is_active column to user table

Revision ID: c04346189431
Revises: 8905ff0b3cc2
Create Date: 2024-04-05 02:40:02.734921

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c04346189431"
down_revision: Union[str, None] = "8905ff0b3cc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pzsd_user",
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pzsd_user", "is_active")
    # ### end Alembic commands ###
